
				<table class="footer-table" width="100%" cellspacing="0" cellpadding="0">
						<tr style=" font-size: 12px; font-weight: 500;">
							<td class="text-left w-25">
							Print: 
							  <?=date("d-m-Y")?>   <?=date("h:i A")?>
							</td>

							<td class="text-center w-25">
							Created By :  <?=find_a_field('user_activity_management','fname','user_id='.$jv->entry_by);?> 							
							</td>
							
							<td class="text-center w-25">
								Printed by: 
								<?=find_a_field('user_activity_management','fname','user_id='.$_SESSION['user']['id'])?> 
								</td>
							<td class="text-center w-25">
							Report is generated by MG IT
							
							</td>
						</tr>
				</table>